version: 1.0.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: v141_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - if "%platform%"=="Win32" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd NppJSONViewer
    - msbuild NppJSONViewer.sln /m /p:configuration="%configuration%" /p:platform="%platform%"

artifacts:
    - path: NppJSONViewer\x64\Release\NPPJSONViewer.dll
      name: x64
    - path: NppJSONViewer\Win32\Release\NPPJSONViewer.dll
      name: Win32
