version: 1.0.{build}
image: Visual Studio 2015


environment:
  matrix:
  - PlatformToolset: v120_xp
  - PlatformToolset: v140_xp

platform:
    - x64
    - Win32

configuration:
    - Unicode Release
    - Unicode Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd NppJSONViewer
    - msbuild NppJSONViewer.sln /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

